# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT", "Enrollment Report"),
                            ("ATTENDANCE", "Attendance Report"),
                            ("ACADEMIC", "Academic Report"),
                            ("FINANCIAL", "Financial Report"),
                            ("STAFF", "Staff Report"),
                            ("INFRASTRUCTURE", "Infrastructure Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("data", models.JSONField(default=dict)),
                ("file", models.FileField(blank=True, upload_to="analytics/reports/")),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("COUNT", "Count"),
                            ("PERCENTAGE", "Percentage"),
                            ("AVERAGE", "Average"),
                            ("RATIO", "Ratio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("academic_year", models.CharField(max_length=9)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
                "ordering": ["name"],
            },
        ),
    ]
