# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsreport",
            index=models.Index(
                fields=["report_type"], name="analytics_a_report__07a16b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsreport",
            index=models.Index(
                fields=["generated_by"], name="analytics_a_generat_06df96_idx"
            ),
        ),
    ]
