# Generated by Django 4.2.7 on 2026-08-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('condition', models.CharField(help_text='e.g., > 35, < 10, == 0', max_length=50)),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('°C', 'Celsius'), ('%', 'Percentage'), ('kWh', 'Kilowatt Hour'), ('L', 'Liters'), ('ppm', 'Parts Per Million'), ('dB', 'Decibels'), ('lux', 'Lux'), ('m³', 'Cubic Meters')], max_length=10)),
                ('min_threshold', models.FloatField(default=0)),
                ('max_threshold', models.FloatField(default=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sensor_types',
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance'), ('ERROR', 'Error')], default='ACTIVE', max_length=15)),
                ('last_reading', models.FloatField(blank=True, null=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='schools.school')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot_dashboard.sensortype')),
            ],
            options={
                'db_table': 'iot_devices',
                'unique_together': {('school', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='IoTAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('value', models.FloatField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot_dashboard.iotdevice')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot_dashboard.alertrule')),
            ],
            options={
                'db_table': 'iot_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='iot_dashboard.iotdevice'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notify_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot_dashboard.iotdevice')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='sensor_read_device__9f0857_idx')],
            },
        ),
    ]
