# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_school_days", models.IntegerField(default=0)),
                ("total_present", models.IntegerField(default=0)),
                ("total_absent", models.IntegerField(default=0)),
                ("total_late", models.IntegerField(default=0)),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "attendance summaries",
                "ordering": ["-academic_year", "-term"],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("remark", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "staff attendances",
                "ordering": ["-date", "staff"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "student attendances",
                "ordering": ["-date", "student"],
            },
        ),
    ]
