# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
        ("schools", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_summaries",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["student"], name="attendance__student_80c9b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(fields=["date"], name="attendance__date_12ec13_idx"),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(fields=["status"], name="attendance__status_938ff8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "date")},
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(fields=["staff"], name="attendance__staff_i_4959e6_idx"),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(fields=["date"], name="attendance__date_f624bd_idx"),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(fields=["status"], name="attendance__status_0e936b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="staffattendance",
            unique_together={("staff", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("school", "academic_year", "term")},
        ),
    ]
