# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPDActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("WORKSHOP", "Workshop"),
                            ("SEMINAR", "Seminar"),
                            ("CONFERENCE", "Conference"),
                            ("COURSE", "Course"),
                            ("CERTIFICATION", "Certification"),
                            ("MENTORING", "Mentoring"),
                            ("SELF_STUDY", "Self Study"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("provider", models.CharField(max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_participants", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("certificate_available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CPDEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "certificate",
                    models.FileField(blank=True, upload_to="cpd/certificates/"),
                ),
                (
                    "hours_completed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("feedback", models.TextField(blank=True)),
                ("rating", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="CPDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "total_hours_required",
                    models.DecimalField(decimal_places=2, default=40, max_digits=6),
                ),
                (
                    "total_hours_completed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("activities_completed", models.IntegerField(default=0)),
                ("certificates_earned", models.IntegerField(default=0)),
                ("is_compliant", models.BooleanField(default=False)),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-academic_year"],
            },
        ),
    ]
