# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cpd", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpdrecord",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpd_records",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="cpdenrollment",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="cpd.cpdactivity",
            ),
        ),
        migrations.AddField(
            model_name="cpdenrollment",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpd_enrollments",
                to="staff.staff",
            ),
        ),
        migrations.AddIndex(
            model_name="cpdactivity",
            index=models.Index(
                fields=["training_type"], name="cpd_cpdacti_trainin_6c4d9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cpdactivity",
            index=models.Index(fields=["status"], name="cpd_cpdacti_status_f69cef_idx"),
        ),
        migrations.AddIndex(
            model_name="cpdactivity",
            index=models.Index(
                fields=["start_date"], name="cpd_cpdacti_start_d_fe5447_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cpdrecord",
            unique_together={("staff", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="cpdenrollment",
            unique_together={("activity", "staff")},
        ),
    ]
