# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior Secondary School"),
                            ("SENIOR", "Senior Secondary School"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        choices=[
                            ("APAPA", "Apapa"),
                            ("MAINLAND", "Mainland"),
                            ("SURULERE", "Surulere"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("established_date", models.DateField(blank=True, null=True)),
                ("student_capacity", models.IntegerField(default=0)),
                ("current_enrollment", models.IntegerField(default=0)),
                ("number_of_classrooms", models.IntegerField(default=0)),
                ("number_of_staff", models.IntegerField(default=0)),
                ("has_science_lab", models.BooleanField(default=False)),
                ("has_computer_lab", models.BooleanField(default=False)),
                ("has_library", models.BooleanField(default=False)),
                ("has_sports_field", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["lga", "school_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolAcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
    ]
