# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools_as_principal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="vice_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools_as_vice_principal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schoolacademicyear",
            unique_together={("school", "year")},
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["code"], name="schools_sch_code_22aa88_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["school_type"], name="schools_sch_school__8aca5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["lga"], name="schools_sch_lga_bcf27a_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active"], name="schools_sch_is_acti_522730_idx"
            ),
        ),
    ]
