# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("CORRESPONDENCE", "Correspondence"),
                            ("MEMO", "Memo"),
                            ("CIRCULAR", "Circular"),
                            ("REPORT", "Report"),
                            ("MINUTES", "Minutes"),
                            ("POLICY", "Policy"),
                            ("CONTRACT", "Contract"),
                            ("INVOICE", "Invoice"),
                            ("RECEIPT", "Receipt"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("IN_TRANSIT", "In Transit"),
                            ("ARCHIVED", "Archived"),
                            ("CONFIDENTIAL", "Confidential"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="files/attachments/")),
                ("original_filename", models.CharField(max_length=300)),
                ("file_size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                ("is_returned", models.BooleanField(default=False)),
                ("movement_date", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "file movements",
                "ordering": ["-movement_date"],
            },
        ),
    ]
