# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("departments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemovement",
            name="from_holder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_movements_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filemovement",
            name="to_holder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_movements_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="files.file",
            ),
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="files.file",
            ),
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="current_holder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="filemovement",
            index=models.Index(fields=["file"], name="files_filem_file_id_dce77a_idx"),
        ),
        migrations.AddIndex(
            model_name="filemovement",
            index=models.Index(
                fields=["from_holder"], name="files_filem_from_ho_6905d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filemovement",
            index=models.Index(
                fields=["to_holder"], name="files_filem_to_hold_7e9909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filemovement",
            index=models.Index(
                fields=["movement_date"], name="files_filem_movemen_bf1609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_number"], name="files_file_file_nu_09f322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_type"], name="files_file_file_ty_2d7e73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["status"], name="files_file_status_0bd07b_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["created_by"], name="files_file_created_85541d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["current_holder"], name="files_file_current_85af97_idx"
            ),
        ),
    ]
