# Generated by Django 4.2.7 on 2026-08-01 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_make_unit_department_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_file_file_category_filecomment_is_internal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_department', models.CharField(blank=True, max_length=50)),
                ('department_confidence', models.FloatField(default=0)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('sensitivity', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=20)),
                ('file_type_suggestion', models.CharField(blank=True, max_length=50)),
                ('keywords', models.JSONField(default=list)),
                ('overall_confidence', models.FloatField(default=0)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'file classifications',
            },
        ),
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CORRESPONDENCE', 'Correspondence'), ('MEMO', 'Memo'), ('CIRCULAR', 'Circular'), ('REPORT', 'Report'), ('POLICY', 'Policy'), ('CONTRACT', 'Contract'), ('FINANCIAL', 'Financial'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_category', models.CharField(blank=True, max_length=20)),
                ('default_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=20)),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('template_content', models.TextField(blank=True, help_text='Default content/body for files created from this template')),
                ('template_fields', models.JSONField(blank=True, default=dict, help_text='JSON schema for required fields when using this template')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfflineQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('MOVE', 'Move'), ('ARCHIVE', 'Archive')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('INTERNAL', 'Internal')], default='INCOMING', max_length=20)),
                ('default_deadline_hours', models.IntegerField(default=24)),
                ('escalation_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('notification_reminder_hours', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['direction', 'step_name'],
            },
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_format',
            field=models.CharField(blank=True, choices=[('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('csv', 'CSV'), ('txt', 'TXT'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='workflowconfig',
            constraint=models.UniqueConstraint(fields=('step_name', 'direction'), name='unique_step_direction'),
        ),
        migrations.AddField(
            model_name='offlinequeue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_file_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetemplate',
            name='default_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_templates', to='departments.department'),
        ),
        migrations.AddField(
            model_name='fileclassification',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification', to='files.file'),
        ),
        migrations.AddIndex(
            model_name='offlinequeue',
            index=models.Index(fields=['status', 'created_at'], name='files_offli_status_65a7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinequeue',
            index=models.Index(fields=['user', 'status'], name='files_offli_user_id_55bb7b_idx'),
        ),
    ]
