# Generated by Django 4.2.7 on 2026-08-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_make_unit_department_nullable'),
        ('files', '0005_fileclassification_filetemplate_offlinequeue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='assigned_department',
            field=models.ForeignKey(blank=True, help_text='Auto-assigned department based on AI classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_files', to='departments.department'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='current_workflow_step',
            field=models.IntegerField(default=1, help_text='Current step in the file movement workflow'),
        ),
        migrations.AddField(
            model_name='file',
            name='direction',
            field=models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('INTERNAL', 'Internal')], default='INCOMING', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='file',
            name='escalation_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ESCALATED', 'Escalated'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='last_moved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_offline_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='offline_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='expected_completion',
            field=models.DateTimeField(blank=True, help_text='Expected completion datetime for this step', null=True),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='from_location',
            field=models.CharField(blank=True, help_text='Location code where file was before movement', max_length=50),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='to_location',
            field=models.CharField(blank=True, help_text='Location code where file is going', max_length=50),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='workflow_step',
            field=models.IntegerField(default=0, help_text='Workflow step number at time of movement'),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded'), ('RETURNED', 'Returned'), ('ESCALATED', 'Escalated'), ('COMMENTED', 'Commented'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('RECEIVED', 'Received')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['direction'], name='files_file_directi_f8e5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['escalation_status'], name='files_file_escalat_a0de84_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['current_workflow_step'], name='files_file_current_c3ee57_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['assigned_department'], name='files_file_assigne_8e40fd_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['priority', 'status'], name='files_file_priorit_1a139d_idx'),
        ),
        migrations.AddIndex(
            model_name='filemovement',
            index=models.Index(fields=['workflow_step'], name='files_filem_workflo_668cec_idx'),
        ),
        migrations.AddIndex(
            model_name='filemovement',
            index=models.Index(fields=['is_overdue'], name='files_filem_is_over_de4d95_idx'),
        ),
        migrations.AddIndex(
            model_name='filemovement',
            index=models.Index(fields=['from_location', 'to_location'], name='files_filem_from_lo_c85772_idx'),
        ),
    ]
