# Generated by Django 4.2.20 on 2026-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_assigned_department_file_created_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file_format',
            field=models.CharField(blank=True, choices=[('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('csv', 'CSV'), ('txt', 'TXT'), ('access', 'ACCESS'), ('mp3', 'MP3'), ('mp4', 'MP4'), ('other', 'Other')], max_length=20),
        ),
    ]
