# Generated by Django 4.2.7 on 2026-07-23 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PROGRESS_REPORT', 'Progress Report'), ('ATTENDANCE_REPORT', 'Attendance Report'), ('BEHAVIOR_REPORT', 'Behavior Report'), ('EXAM_RESULTS', 'Exam Results'), ('REPORT_CARD', 'Report Card')], max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_student_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_student_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTAMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('PARENT_TEACHER', 'Parent-Teacher Conference'), ('PROGRESS_REVIEW', 'Progress Review'), ('DISCIPLINARY', 'Disciplinary Meeting'), ('ACADEMIC_SUPPORT', 'Academic Support'), ('CAREER_GUIDANCE', 'Career Guidance'), ('GENERAL', 'General Meeting')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('venue', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=15)),
                ('minutes', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('follow_up_actions', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees_parents', models.ManyToManyField(blank=True, related_name='pta_attendees', to=settings.AUTH_USER_MODEL)),
                ('organized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_pta_meetings', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pta_meetings', to='schools.school')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ParentTeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Update'), ('BEHAVIOR', 'Behavior Update'), ('ATTENDANCE', 'Attendance'), ('EVENTS', 'School Events'), ('FEES', 'Fees & Payments'), ('GENERAL', 'General'), ('URGENT', 'Urgent')], default='GENERAL', max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent_reply', models.TextField(blank=True)),
                ('parent_replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_sent_messages', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_messages', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
