# Generated by Django 4.2.7 on 2026-08-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web Browser')], max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_tokens',
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('RESULTS', 'Exam Results'), ('ATTENDANCE', 'Attendance Alert'), ('FEES', 'Fee Reminder'), ('ANNOUNCEMENT', 'School Announcement'), ('EMERGENCY', 'Emergency Alert'), ('ASSIGNMENT', 'Assignment'), ('EVENT', 'School Event'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('target_roles', models.JSONField(default=list, help_text='Target specific roles')),
                ('data', models.JSONField(default=dict, help_text='Additional data payload')),
                ('image_url', models.URLField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_schools', models.ManyToManyField(blank=True, related_name='push_notifications', to='schools.school')),
                ('target_users', models.ManyToManyField(blank=True, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('FAILED', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_notifications.devicetoken')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='push_notifications.pushnotification')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
