# Generated by Django 4.2.7 on 2026-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='courses/thumbnails/'),
        ),
    ]
