# Generated by Django 4.2.30 on 2026-08-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_usersession_device_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privilege",
            name="role",
            field=models.CharField(
                choices=[
                    ("SYSADMIN", "System Administrator"),
                    ("TG_PS", "Tutor General/Permanent Secretary"),
                    ("HR", "Admin & HR Head"),
                    ("FIN", "Finance Director"),
                    ("AUDIT", "Internal Audit Head"),
                    ("QA", "Quality Assurance Head"),
                    ("CC", "Co-Curricular Head"),
                    ("EMIS", "EMIS Head"),
                    ("PLAN", "Planning Head"),
                    ("PROC", "Procurement Head"),
                    ("PA", "Public Affairs Head"),
                    ("SA", "Schools Admin Head"),
                    ("FRENCH", "French Unit Head"),
                    ("REG", "Registry Head"),
                    ("PRI", "Principal"),
                    ("VP", "Vice Principal"),
                    ("TCH", "Teacher"),
                    ("STD", "Student"),
                    ("PAR", "Parent"),
                    ("REG_OFF", "Registry Officer"),
                    ("SA_OFF", "School Admin Officer"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="roleprivilege",
            name="role",
            field=models.CharField(
                choices=[
                    ("SYSADMIN", "System Administrator"),
                    ("TG_PS", "Tutor General/Permanent Secretary"),
                    ("HR", "Admin & HR Head"),
                    ("FIN", "Finance Director"),
                    ("AUDIT", "Internal Audit Head"),
                    ("QA", "Quality Assurance Head"),
                    ("CC", "Co-Curricular Head"),
                    ("EMIS", "EMIS Head"),
                    ("PLAN", "Planning Head"),
                    ("PROC", "Procurement Head"),
                    ("PA", "Public Affairs Head"),
                    ("SA", "Schools Admin Head"),
                    ("FRENCH", "French Unit Head"),
                    ("REG", "Registry Head"),
                    ("PRI", "Principal"),
                    ("VP", "Vice Principal"),
                    ("TCH", "Teacher"),
                    ("STD", "Student"),
                    ("PAR", "Parent"),
                    ("REG_OFF", "Registry Officer"),
                    ("SA_OFF", "School Admin Officer"),
                ],
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SYSADMIN", "System Administrator"),
                    ("TG_PS", "Tutor General/Permanent Secretary"),
                    ("HR", "Admin & HR Head"),
                    ("FIN", "Finance Director"),
                    ("AUDIT", "Internal Audit Head"),
                    ("QA", "Quality Assurance Head"),
                    ("CC", "Co-Curricular Head"),
                    ("EMIS", "EMIS Head"),
                    ("PLAN", "Planning Head"),
                    ("PROC", "Procurement Head"),
                    ("PA", "Public Affairs Head"),
                    ("SA", "Schools Admin Head"),
                    ("FRENCH", "French Unit Head"),
                    ("REG", "Registry Head"),
                    ("PRI", "Principal"),
                    ("VP", "Vice Principal"),
                    ("TCH", "Teacher"),
                    ("STD", "Student"),
                    ("PAR", "Parent"),
                    ("REG_OFF", "Registry Officer"),
                    ("SA_OFF", "School Admin Officer"),
                ],
                default="STD",
                max_length=10,
            ),
        ),
    ]
