# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("SPORTS", "Sports"),
                            ("CLUB", "Club"),
                            ("SOCIETY", "Society"),
                            ("COMPETITION", "Competition"),
                            ("CULTURAL", "Cultural Activity"),
                            ("SCIENCE", "Science Activity"),
                            ("DEBATE", "Debate"),
                            ("PRESS", "Press Club"),
                            ("ENVIRONMENTAL", "Environmental Club"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("meeting_schedule", models.CharField(blank=True, max_length=200)),
                ("meeting_venue", models.CharField(blank=True, max_length=200)),
                ("max_participants", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school", "activity_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("joined_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["activity", "student"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("SPORTS", "Sports"),
                            ("CLUB", "Club"),
                            ("SOCIETY", "Society"),
                            ("COMPETITION", "Competition"),
                            ("CULTURAL", "Cultural Activity"),
                            ("SCIENCE", "Science Activity"),
                            ("DEBATE", "Debate"),
                            ("PRESS", "Press Club"),
                            ("ENVIRONMENTAL", "Environmental Club"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("organizer", models.CharField(max_length=200)),
                ("venue", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_deadline", models.DateField()),
                ("max_participants", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True, upload_to="competitions/certificates/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="co_curricular.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["competition", "position"],
            },
        ),
    ]
