# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("co_curricular", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionentry",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_entries",
                to="schools.school",
            ),
        ),
    ]
