# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("co_curricular", "0002_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionentry",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_entries",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["competition_type"], name="co_curricul_competi_3ad4ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["start_date"], name="co_curricul_start_d_71c7bd_idx"
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="co_curricular.activity",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_participations",
                to="students.student",
            ),
        ),
    ]
