# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("co_curricular", "0003_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="schools.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="competitionentry",
            unique_together={("competition", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "student")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["school"], name="co_curricul_school__7d0dea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_type"], name="co_curricul_activit_5a3a7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["is_active"], name="co_curricul_is_acti_1f9dac_idx"
            ),
        ),
    ]
