# Generated by Django 4.2.30 on 2026-07-18 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=20, unique=True)),
                ("employee_number", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TEACHING", "Teaching Staff"),
                            ("NON_TEACHING", "Non-Teaching Staff"),
                            ("ADMINISTRATIVE", "Administrative Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("PRINCIPAL", "Principal"),
                            ("VICE_PRINCIPAL", "Vice Principal"),
                            ("HEAD_TEACHER", "Head Teacher"),
                            ("SENIOR_TEACHER", "Senior Teacher"),
                            ("TEACHER", "Teacher"),
                            ("LIBRARIAN", "Librarian"),
                            ("LABORATORY_ATTENDANT", "Laboratory Attendant"),
                            ("BURSAR", "Bursar"),
                            ("SECRETARY", "Secretary"),
                            ("CLERK", "Clerk"),
                            ("GARDENER", "Gardener"),
                            ("SECURITY", "Security"),
                            ("CLEANER", "Cleaner"),
                            ("DRIVER", "Driver"),
                            ("TECHNICIAN", "Technician"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                            ("VOLUNTEER", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("PhD", "Doctorate"),
                            ("Masters", "Masters Degree"),
                            ("Bachelors", "Bachelors Degree"),
                            ("HND", "Higher National Diploma"),
                            ("OND", "Ordinary National Diploma"),
                            ("NCE", "Nigeria Certificate in Education"),
                            ("SSCE", "Senior School Certificate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state_of_origin", models.CharField(max_length=50)),
                ("lga_of_origin", models.CharField(max_length=50)),
                ("residential_address", models.TextField()),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=20)),
                ("bank_account_name", models.CharField(max_length=200)),
                ("pension_pin", models.CharField(blank=True, max_length=20)),
                ("tax_id", models.CharField(blank=True, max_length=20)),
                ("date_joined", models.DateField()),
                ("date_of_first_appointment", models.DateField(blank=True, null=True)),
                ("date_of_retirement", models.DateField(blank=True, null=True)),
                ("grade_level", models.CharField(blank=True, max_length=20)),
                (
                    "step",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(17),
                        ],
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("suspension_reason", models.TextField(blank=True)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, upload_to="staff/photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["staff_id"],
            },
        ),
        migrations.CreateModel(
            name="StaffLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("SICK", "Sick Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("COMPASSIONATE", "Compassionate Leave"),
                            ("STUDY", "Study Leave"),
                            ("EDUCATIONAL", "Educational Leave"),
                            ("EXAMINATION", "Examination Leave"),
                            ("CASUAL", "Casual Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("SATISFACTORY", "Satisfactory"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement"),
                            ("UNSATISFACTORY", "Unsatisfactory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "punctuality_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "dedication_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "teaching_quality_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "student_performance_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("review_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-academic_year", "-term"],
            },
        ),
    ]
