# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0001_initial"),
        ("schools", "0002_initial"),
        ("departments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffperformance",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performance_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffperformance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staffleave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffleave",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="staffperformance",
            index=models.Index(
                fields=["academic_year"], name="staff_staff_academi_dbe379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffperformance",
            index=models.Index(fields=["rating"], name="staff_staff_rating_0372bc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="staffperformance",
            unique_together={("staff", "academic_year", "term")},
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(
                fields=["leave_type"], name="staff_staff_leave_t_a897b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffleave",
            index=models.Index(fields=["status"], name="staff_staff_status_7f5e8d_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["staff_id"], name="staff_staff_staff_i_1228db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["employee_number"], name="staff_staff_employe_1b06ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["category"], name="staff_staff_categor_10f8da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["designation"], name="staff_staff_designa_1ae0e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["school"], name="staff_staff_school__032c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["is_active"], name="staff_staff_is_acti_0db61a_idx"
            ),
        ),
    ]
