# Generated by Django 4.2.7 on 2026-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='staff/photos/'),
        ),
    ]
