# Generated by Django 4.2.7 on 2026-08-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ATTENDANCE_DROP', 'Attendance Drop'), ('GRADE_DECLINE', 'Grade Decline'), ('DISCIPLINE_SPIKE', 'Discipline Spike'), ('FEE_DEFAULT', 'Fee Default'), ('DROPOUT_RISK', 'Dropout Risk'), ('ABSENCE_STREAK', 'Absence Streak')], max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0, help_text='0-100 risk score')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=10)),
                ('attendance_risk', models.FloatField(default=0.0, help_text='Risk from attendance patterns')),
                ('academic_risk', models.FloatField(default=0.0, help_text='Risk from grade trends')),
                ('discipline_risk', models.FloatField(default=0.0, help_text='Risk from disciplinary records')),
                ('financial_risk', models.FloatField(default=0.0, help_text='Risk from fee payment patterns')),
                ('engagement_risk', models.FloatField(default=0.0, help_text='Risk from participation levels')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of identified risk factors')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='AI-generated intervention recommendations')),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='students.student')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='RiskTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=10)),
                ('attendance_risk', models.FloatField(default=0.0)),
                ('academic_risk', models.FloatField(default=0.0)),
                ('discipline_risk', models.FloatField(default=0.0)),
                ('financial_risk', models.FloatField(default=0.0)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_trends', to='students.student')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('COUNSELING', 'Counseling Session'), ('PARENT_MEETING', 'Parent Meeting'), ('ACADEMIC_SUPPORT', 'Academic Support'), ('FINANCIAL_AID', 'Financial Aid'), ('MENTORING', 'Mentoring Program'), ('DISCIPLINE_REVIEW', 'Discipline Review'), ('SCHEDULE_ADJUSTMENT', 'Schedule Adjustment'), ('PEER_SUPPORT', 'Peer Support'), ('CUSTOM', 'Custom Intervention')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('outcome', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='predictive_analytics.earlywarningalert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='earlywarningalert',
            name='risk_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='predictive_analytics.studentriskprofile'),
        ),
        migrations.AddField(
            model_name='earlywarningalert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warnings', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['risk_level'], name='predictive__risk_le_856811_idx'),
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['-risk_score'], name='predictive__risk_sc_ad0e21_idx'),
        ),
        migrations.AddIndex(
            model_name='studentriskprofile',
            index=models.Index(fields=['last_analyzed'], name='predictive__last_an_761acd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='risktrend',
            unique_together={('student', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='earlywarningalert',
            index=models.Index(fields=['alert_type', 'acknowledged'], name='predictive__alert_t_249c68_idx'),
        ),
        migrations.AddIndex(
            model_name='earlywarningalert',
            index=models.Index(fields=['-created_at'], name='predictive__created_cea534_idx'),
        ),
    ]
