# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0001_initial"),
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="timetable.timetable",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="teachertimetable",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teachertimetable",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_timetables",
                to="timetable.timetable",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schools.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={("timetable", "day", "period")},
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("school", "class_obj", "academic_year", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="teachertimetable",
            unique_together={("teacher", "timetable")},
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("school", "period_number")},
        ),
    ]
