# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Correspondence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INCOMING", "Incoming"),
                            ("OUTGOING", "Outgoing"),
                            ("INTERNAL", "Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender", models.CharField(max_length=200)),
                ("recipient", models.CharField(max_length=200)),
                ("date_received", models.DateField()),
                ("date_sent", models.DateField(blank=True, null=True)),
                ("subject", models.CharField(max_length=300)),
                ("is_urgent", models.BooleanField(default=False)),
                ("requires_response", models.BooleanField(default=False)),
                ("response_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CORRESPONDENCE", "Correspondence"),
                            ("MEMO", "Memo"),
                            ("CIRCULAR", "Circular"),
                            ("REPORT", "Report"),
                            ("MINUTES", "Minutes"),
                            ("POLICY", "Policy"),
                            ("CONTRACT", "Contract"),
                            ("LETTER", "Letter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("content", models.TextField()),
                ("file", models.FileField(upload_to="registry/versions/")),
                ("changes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_code", models.CharField(max_length=50)),
                ("box_number", models.CharField(blank=True, max_length=20)),
                ("shelf_number", models.CharField(blank=True, max_length=20)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("filed_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filings",
                        to="registry.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-filed_date"],
            },
        ),
    ]
