# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="filed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="registry.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correspondence",
                to="registry.document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version_number")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["reference_number"], name="registry_do_referen_5e9bb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="registry_do_documen_a95341_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="registry_do_status_00d04d_idx"),
        ),
    ]
