# Generated by Django 4.2.30 on 2026-09-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_document_attachment"),
        ("registry", "0003_add_memo_workflow_models"),
    ]

    operations = []
