# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellnessResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("ARTICLE", "Article"),
                            ("VIDEO", "Video"),
                            ("CONTACT", "Contact"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_emergency", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WellnessCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("GREAT", "Great"),
                            ("GOOD", "Good"),
                            ("OKAY", "Okay"),
                            ("SAD", "Sad"),
                            ("ANXIOUS", "Anxious"),
                            ("ANGRY", "Angry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stress_level", models.IntegerField(default=5)),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("exercise_minutes", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("concerns", models.TextField(blank=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_checkins",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="wellness_we_student_f57500_idx"
                    ),
                    models.Index(fields=["date"], name="wellness_we_date_706a60_idx"),
                    models.Index(fields=["mood"], name="wellness_we_mood_3b2e90_idx"),
                    models.Index(
                        fields=["is_flagged"], name="wellness_we_is_flag_a54a4f_idx"
                    ),
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="CounselingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counseling_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic"),
                            ("BEHAVIORAL", "Behavioral"),
                            ("EMOTIONAL", "Emotional"),
                            ("SOCIAL", "Social"),
                            ("CAREER", "Career"),
                            ("PERSONAL", "Personal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField()),
                ("session_time", models.TimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                ("notes", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="wellness_co_student_574627_idx"
                    ),
                    models.Index(
                        fields=["counselor"], name="wellness_co_counsel_5eea15_idx"
                    ),
                    models.Index(
                        fields=["session_date"], name="wellness_co_session_52d7cc_idx"
                    ),
                ],
            },
        ),
    ]
