# Generated by Django 4.2.7 on 2026-08-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('students', '0003_alter_student_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('TRANScript', 'Transcript'), ('LEAVING', 'Leaving Certificate'), ('MERIT', 'Merit Certificate'), ('PARTICIPATION', 'Participation Certificate'), ('ATHLETIC', 'Athletic Certificate'), ('ACADEMIC', 'Academic Excellence'), ('CUSTOM', 'Custom Certificate')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cert_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('block_data', models.JSONField(default=dict)),
                ('principal_signature', models.CharField(blank=True, max_length=500)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.TextField(blank=True)),
                ('verified_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_certificates', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_certificates', to='students.student')),
            ],
            options={
                'db_table': 'blockchain_certificates',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.CharField(max_length=200)),
                ('verification_method', models.CharField(choices=[('QR_CODE', 'QR Code Scan'), ('HASH', 'Hash Lookup'), ('URL', 'Direct URL'), ('API', 'API Verification')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('is_valid', models.BooleanField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='blockchain_cert.certificate')),
            ],
            options={
                'db_table': 'certificate_verifications',
                'ordering': ['-verified_at'],
            },
        ),
    ]
