# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERSONNEL", "Personnel Costs"),
                            ("CAPITAL", "Capital Expenditure"),
                            ("RECURRENT", "Recurrent Expenditure"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SUPPLIES", "Supplies"),
                            ("UTILITIES", "Utilities"),
                            ("TRANSPORT", "Transport"),
                            ("TRAINING", "Training"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school", "academic_year", "category"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition Fee"),
                            ("DEVELOPMENT", "Development Levy"),
                            ("SPORTS", "Sports Fee"),
                            ("LIBRARY", "Library Fee"),
                            ("LABORATORY", "Laboratory Fee"),
                            ("EXAMINATION", "Examination Fee"),
                            ("ICT", "ICT Fee"),
                            ("PTA", "PTA Levy"),
                            ("INSURANCE", "Insurance"),
                            ("MEDICAL", "Medical Fee"),
                            ("TRANSPORT", "Transport Fee"),
                            ("UNIFORM", "Uniform Fee"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("class_level", models.CharField(blank=True, max_length=20)),
                ("is_compulsory", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school", "academic_year", "term", "fee_type"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("ONLINE", "Online Payment"),
                            ("POS", "POS"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETED", "Completed"),
                            ("OVERPAID", "Overpaid"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fees",
                        to="finance.feestructure",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
