# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student_fee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.studentfee",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["student"], name="finance_stu_student_bf9d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(fields=["status"], name="finance_stu_status_324f93_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentfee",
            unique_together={("student", "fee_structure")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["reference_number"], name="finance_pay_referen_153f1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="finance_pay_payment_72f761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["is_confirmed"], name="finance_pay_is_conf_eb4606_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["school"], name="finance_fee_school__a3f6b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["fee_type"], name="finance_fee_fee_typ_f5cdd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["academic_year"], name="finance_fee_academi_7e4cd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["school"], name="finance_bud_school__139aa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["category"], name="finance_bud_categor_5f83b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["academic_year"], name="finance_bud_academi_5b2f80_idx"
            ),
        ),
    ]
