# Generated by Django 4.2.7 on 2026-07-23 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_initial'),
        ('schools', '0002_initial'),
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('funding_source', models.CharField(help_text='Organization or government body providing the grant', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=9)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_utilized', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conditions', models.TextField(blank=True, help_text='Terms and conditions of the grant')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grants', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grants', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='departments.department')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='finance_gra_status_0c0a6a_idx'), models.Index(fields=['funding_source'], name='finance_gra_funding_e8288e_idx'), models.Index(fields=['academic_year'], name='finance_gra_academi_60c8a8_idx')],
            },
        ),
    ]
