# Generated by Django 4.2.7 on 2026-08-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('students', '0003_alter_student_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('class_average', models.FloatField(default=0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True)),
                ('teacher_remark', models.TextField(blank=True)),
                ('principal_remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report_cards', to='students.student')),
            ],
            options={
                'db_table': 'generated_report_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_type', models.CharField(blank=True, max_length=50)),
                ('header_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('include_photo', models.BooleanField(default=True)),
                ('include_signature', models.BooleanField(default=True)),
                ('include_remarks', models.BooleanField(default=True)),
                ('include_class_average', models.BooleanField(default=True)),
                ('include_position', models.BooleanField(default=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report_card_templates',
            },
        ),
        migrations.CreateModel(
            name='ReportCardShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('DOWNLOAD', 'Download'), ('PRINT', 'Print')], max_length=15)),
                ('recipient', models.CharField(max_length=200)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='report_card_gen.generatedreportcard')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_card_share_logs',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedreportcard',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_card_gen.reportcardtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedreportcard',
            unique_together={('student', 'academic_session', 'term')},
        ),
    ]
