# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TERM_START", "Term Start"),
                            ("TERM_END", "Term End"),
                            ("MIDTERM", "Mid-Term Break"),
                            ("HOLIDAY", "Holiday"),
                            ("EXAM_PERIOD", "Examination Period"),
                            ("RESULT_RELEASE", "Result Release"),
                            ("PARENT_TEACHER", "Parent-Teacher Meeting"),
                            ("SCHOOL_EVENT", "School Event"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_recurring", models.BooleanField(default=False)),
                ("academic_year", models.CharField(max_length=9)),
                ("term", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("JSS1", "Junior Secondary School 1"),
                            ("JSS2", "Junior Secondary School 2"),
                            ("JSS3", "Junior Secondary School 3"),
                            ("SS1", "Senior Secondary School 1"),
                            ("SS2", "Senior Secondary School 2"),
                            ("SS3", "Senior Secondary School 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=10)),
                ("capacity", models.IntegerField(default=40)),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school", "level", "section"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "class subjects",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("CA1", "Continuous Assessment 1"),
                            ("CA2", "Continuous Assessment 2"),
                            ("CA3", "Continuous Assessment 3"),
                            ("MIDTERM", "Mid-Term Exam"),
                            ("FINAL", "Final Exam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_marks", models.IntegerField(default=100)),
                ("pass_marks", models.IntegerField(default=40)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-academic_year", "-term", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=5)),
                ("remark", models.CharField(blank=True, max_length=100)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["student", "subject"],
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("class_position", models.IntegerField(blank=True, null=True)),
                ("total_students", models.IntegerField(blank=True, null=True)),
                ("teacher_remark", models.TextField(blank=True)),
                ("principal_remark", models.TextField(blank=True)),
                ("next_term_begins", models.DateField(blank=True, null=True)),
                ("is_released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "report cards",
                "ordering": ["-academic_year", "-term"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCIENCE", "Science"),
                            ("ARTS", "Arts"),
                            ("COMMERCIAL", "Commercial"),
                            ("TECHNICAL", "Technical"),
                            ("GENERAL", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_compulsory", models.BooleanField(default=False)),
                ("applicable_levels", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="academics_s_code_3689e5_idx"),
                    models.Index(
                        fields=["category"], name="academics_s_categor_5c5105_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRANSFERRED", "Transferred"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("GRADUATED", "Graduated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("previous_class", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="academics.class",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "student enrollments",
                "ordering": ["-academic_year", "-term"],
            },
        ),
    ]
