# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0002_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="entered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entered_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="academics.exam",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_calendar",
                to="schools.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "class_obj", "academic_year", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student", "academic_year", "term")},
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["student"], name="academics_e_student_304068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(fields=["exam"], name="academics_e_exam_id_d1bcd8_idx"),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["subject"], name="academics_e_subject_0d8e26_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("student", "exam", "subject")},
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["school"], name="academics_e_school__4ea135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["exam_type"], name="academics_e_exam_ty_b1514a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["academic_year"], name="academics_e_academi_962e99_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school"], name="academics_c_school__bd4381_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["level"], name="academics_c_level_0c85df_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["academic_year"], name="academics_c_academi_3e0641_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("school", "name", "academic_year", "term")},
        ),
        migrations.AddIndex(
            model_name="academiccalendar",
            index=models.Index(
                fields=["school"], name="academics_a_school__4eade6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academiccalendar",
            index=models.Index(
                fields=["event_type"], name="academics_a_event_t_0279ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academiccalendar",
            index=models.Index(
                fields=["academic_year"], name="academics_a_academi_ed579e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academiccalendar",
            index=models.Index(
                fields=["start_date"], name="academics_a_start_d_8bc157_idx"
            ),
        ),
    ]
