# Generated by Django 4.2.20 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_gradingscale_gradeboundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
