# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alumni", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnimember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alumni_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumnievent",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_alumni_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumnidonation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="alumni.alumnimember",
            ),
        ),
        migrations.AddIndex(
            model_name="alumnimember",
            index=models.Index(
                fields=["school"], name="alumni_alum_school__3e0275_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumnimember",
            index=models.Index(
                fields=["graduation_year"], name="alumni_alum_graduat_efd067_idx"
            ),
        ),
    ]
