# Generated by Django 4.2.7 on 2026-08-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('yo', 'Yoruba'), ('pcm', 'Nigerian Pidgin'), ('fr', 'French')], default='en', max_length=5)),
                ('auto_detect', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_language_preferences',
            },
        ),
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('language', models.CharField(max_length=5)),
                ('value', models.TextField()),
                ('context', models.CharField(blank=True, max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'translation_entries',
                'unique_together': {('key', 'language', 'context')},
            },
        ),
    ]
