# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("infrastructure", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_maintenance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="infrastructure.facility",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilities",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["school"], name="infrastruct_school__ccb80c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="infrastruct_status_8e95a3_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["facility"], name="infrastruct_facilit_3f6109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(fields=["status"], name="infrastruct_status_8108f4_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["priority"], name="infrastruct_priorit_9f8522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["school"], name="infrastruct_school__fe61ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["facility_type"], name="infrastruct_facilit_2742e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["condition"], name="infrastruct_conditi_bfb679_idx"
            ),
        ),
    ]
