# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discipline", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinaryincident",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disciplinaryincident",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="behaviorplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_behavior_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="behaviorplan",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_plans",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryincident",
            index=models.Index(
                fields=["student"], name="discipline__student_0dd0a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryincident",
            index=models.Index(
                fields=["incident_type"], name="discipline__inciden_0887b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryincident",
            index=models.Index(
                fields=["severity"], name="discipline__severit_26d297_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryincident",
            index=models.Index(fields=["status"], name="discipline__status_f81ba4_idx"),
        ),
        migrations.AddIndex(
            model_name="disciplinaryincident",
            index=models.Index(
                fields=["incident_date"], name="discipline__inciden_b2dccd_idx"
            ),
        ),
    ]
