# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_number", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("nationality", models.CharField(default="Nigerian", max_length=50)),
                ("state_of_origin", models.CharField(max_length=50)),
                ("lga_of_origin", models.CharField(max_length=50)),
                ("residential_address", models.TextField()),
                ("parent_name", models.CharField(max_length=200)),
                ("parent_phone", models.CharField(max_length=20)),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("parent_occupation", models.CharField(blank=True, max_length=100)),
                ("parent_address", models.TextField(blank=True)),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                ("guardian_phone", models.CharField(blank=True, max_length=20)),
                ("medical_conditions", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("admission_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("EXPELLED", "Expelled"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(blank=True, upload_to="students/photos/"),
                ),
                ("is_boarding", models.BooleanField(default=False)),
                ("bus_route", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["admission_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField()),
                ("condition", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("treatment", models.TextField(blank=True)),
                ("medication", models.TextField(blank=True)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                ("hospital", models.CharField(blank=True, max_length=200)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "student medical records",
                "ordering": ["-record_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("UNCLE", "Uncle"),
                            ("AUNT", "Aunt"),
                            ("SIBLING", "Sibling"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary"],
            },
        ),
    ]
