# Generated by Django 4.2.7 on 2026-07-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='students/photos/'),
        ),
    ]
