# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("layout", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic Report"),
                            ("FINANCIAL", "Financial Report"),
                            ("ATTENDANCE", "Attendance Report"),
                            ("STAFF", "Staff Report"),
                            ("INSPECTION", "Inspection Report"),
                            ("ENROLLMENT", "Enrollment Report"),
                            ("PERFORMANCE", "Performance Report"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("file", models.FileField(blank=True, upload_to="reports/")),
                ("is_scheduled", models.BooleanField(default=False)),
                ("schedule_cron", models.CharField(blank=True, max_length=50)),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("STAT_CARD", "Statistic Card"),
                            ("LINE_CHART", "Line Chart"),
                            ("BAR_CHART", "Bar Chart"),
                            ("PIE_CHART", "Pie Chart"),
                            ("TABLE", "Data Table"),
                            ("MAP", "Map"),
                            ("PROGRESS", "Progress Bar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_source", models.CharField(max_length=200)),
                ("config", models.JSONField(default=dict)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=6)),
                ("height", models.IntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="reports.dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
    ]
