# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type"], name="reports_rep_report__dbb097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_by"], name="reports_rep_generat_4dc4d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(fields=["owner"], name="reports_das_owner_i_2c0495_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["is_default"], name="reports_das_is_defa_dff9e2_idx"
            ),
        ),
    ]
