# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine Inspection"),
                            ("SURPRISE", "Surprise Inspection"),
                            ("FOLLOW_UP", "Follow-up Inspection"),
                            ("SPECIAL", "Special Inspection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("objectives", models.TextField()),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("SATISFACTORY", "Satisfactory"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement"),
                            ("UNSATISFACTORY", "Unsatisfactory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "report_file",
                    models.FileField(blank=True, upload_to="inspections/reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="InspectionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["due_date", "status"],
            },
        ),
        migrations.CreateModel(
            name="InspectionChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("item", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("SATISFACTORY", "Satisfactory"),
                            ("POOR", "Poor"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "evidence_file",
                    models.FileField(blank=True, upload_to="inspections/evidence/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "inspection checklists",
                "ordering": ["category", "item"],
            },
        ),
    ]
