# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionaction",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspection_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspectionaction",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="inspection.inspection",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="lead_inspector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="led_inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="team_members",
            field=models.ManyToManyField(
                related_name="inspection_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["school"], name="inspection__school__00f1d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["inspection_type"], name="inspection__inspect_300b5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["status"], name="inspection__status_059dcd_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["scheduled_date"], name="inspection__schedul_13aeb7_idx"
            ),
        ),
    ]
