# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0002_initial"),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="studenttransport",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assignments",
                to="transport.busroute",
            ),
        ),
        migrations.AddField(
            model_name="studenttransport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_assignments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="busroute",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_routes",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="busroute",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="transport.vehicle",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studenttransport",
            unique_together={("student", "route", "academic_year")},
        ),
    ]
