# Generated by Django 4.2.7 on 2026-07-24 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0003_make_unit_department_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_number', models.CharField(max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_organization', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('date_received', models.DateField()),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('subject_category', models.CharField(choices=[('LETTER', 'Letter'), ('MEMO', 'Memo'), ('CIRCULAR', 'Circular'), ('INVITE', 'Invitation'), ('COMPLAINT', 'Complaint'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('SCANNED', 'Scanned'), ('CLASSIFIED', 'Classified'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('IN_ACTION', 'In Action'), ('RESPONDED', 'Responded'), ('DISPATCHED', 'Dispatched'), ('ARCHIVED', 'Archived')], default='RECEIVED', max_length=20)),
                ('scanned_copy', models.FileField(blank=True, upload_to='mail/scans/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_mails', to='departments.department')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('scan_notes', models.TextField(blank=True)),
                ('attachment_count', models.IntegerField(default=0)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='mail_workflow.incomingmail')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='MailMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_sent', to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mail_workflow.incomingmail')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mail movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='MailAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('action_required', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20)),
                ('response_notes', models.TextField(blank=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mail_workflow.incomingmail')),
            ],
            options={
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='incomingmail',
            index=models.Index(fields=['mail_number'], name='mail_workfl_mail_nu_dd2d95_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingmail',
            index=models.Index(fields=['status'], name='mail_workfl_status_044b64_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingmail',
            index=models.Index(fields=['date_received'], name='mail_workfl_date_re_a7a521_idx'),
        ),
    ]
