# Generated by Django 4.2.7 on 2026-07-25 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0003_make_unit_department_nullable'),
        ('schools', '0002_initial'),
        ('mail_workflow', '0001_initial_mail_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('correspondence_type', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('INTERNAL', 'Internal'), ('SCHOOL_HQ', 'School-HQ'), ('HQ_SCHOOL', 'HQ-School'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTERED', 'Registered'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted'), ('TOP_SECRET', 'Top Secret')], default='CONFIDENTIAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondences', to='departments.department')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_correspondences', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondences', to='schools.school')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_correspondences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_organization', models.CharField(blank=True, max_length=300)),
                ('recipient_address', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_dispatched', models.DateField(blank=True, null=True)),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted'), ('TOP_SECRET', 'Top Secret')], default='CONFIDENTIAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('scanned_copy', models.FileField(blank=True, upload_to='mail/outgoing/scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_outgoing_mails', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_mails', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHQCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('SCHOOL_TO_HQ', 'School to HQ'), ('HQ_TO_SCHOOL', 'HQ to School')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted'), ('TOP_SECRET', 'Top Secret')], default='CONFIDENTIAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RECEIVED_AT_HQ', 'Received at HQ'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTION_REQUIRED', 'Action Required'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('requires_response', models.BooleanField(default=False)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_correspondences', to='departments.department')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_hq_correspondences', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_correspondences', to='schools.school')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_hq_correspondences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHQCorrespondenceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mail_workflow.schoolhqcorrespondence')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hq_correspondence_sent', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_correspondence_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'school HQ correspondence movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingMailMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_mail_sent', to=settings.AUTH_USER_MODEL)),
                ('outgoing_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mail_workflow.outgoingmail')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_mail_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'outgoing mail movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingMailApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_mail_approvals', to=settings.AUTH_USER_MODEL)),
                ('outgoing_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mail_workflow.outgoingmail')),
            ],
            options={
                'ordering': ['approval_order'],
            },
        ),
        migrations.CreateModel(
            name='MailCorrespondenceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mail_workflow.mailcorrespondence')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_sent', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mail correspondence movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolhqcorrespondence',
            index=models.Index(fields=['reference_number'], name='mail_workfl_referen_581eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolhqcorrespondence',
            index=models.Index(fields=['direction'], name='mail_workfl_directi_793ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolhqcorrespondence',
            index=models.Index(fields=['status'], name='mail_workfl_status_276a64_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingmail',
            index=models.Index(fields=['mail_number'], name='mail_workfl_mail_nu_9f2f71_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingmail',
            index=models.Index(fields=['status'], name='mail_workfl_status_53d79a_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingmail',
            index=models.Index(fields=['date_created'], name='mail_workfl_date_cr_f3e8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='mailcorrespondence',
            index=models.Index(fields=['reference_number'], name='mail_workfl_referen_929091_idx'),
        ),
        migrations.AddIndex(
            model_name='mailcorrespondence',
            index=models.Index(fields=['correspondence_type'], name='mail_workfl_corresp_4778a8_idx'),
        ),
        migrations.AddIndex(
            model_name='mailcorrespondence',
            index=models.Index(fields=['status'], name='mail_workfl_status_27b860_idx'),
        ),
    ]
